///////////////////////////////////////////////////////////
//  RotateDirection.cs
//  Implementation of the Enumeration RotateDirection
//  Generated by Enterprise Architect
//  Created on:      30-May-2021 2:56:55 PM
//  Original author: Reza
///////////////////////////////////////////////////////////

namespace FireByte
{
    public enum RotateDirection
    {
        YAxis,
        XAxis,
        ZAxis,
    } //end RotateDirection
} //end namespace FireByte